# 本系统密钥信息
KeyPair:
  PublicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCdE7sNOciNv804wDusYOpCcbUXVr3tB33YPN2MxK0birHVq3c5EBt3ssbIh/1HSmQgDvZD3YCqyyLGqTDVU1M0qsx/fRcej+CMVNy28dN1sAtzKFWmSybVUI/ue9bB+R5wGkmsn10k0+bCRGaw/qs1QjOv8pkpW2RFPGA73QiwGwIDAQAB
  PrivateKey: MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBAJ0Tuw05yI2/zTjAO6xg6kJxtRdWve0Hfdg83YzErRuKsdWrdzkQG3eyxsiH/UdKZCAO9kPdgKrLIsapMNVTUzSqzH99Fx6P4IxU3Lbx03WwC3MoVaZLJtVQj+571sH5HnAaSayfXSTT5sJEZrD+qzVCM6/ymSlbZEU8YDvdCLAbAgMBAAECgYAXtrDYkE6sx7YNyUe5AHCdU1lJirjlnenryVSROegAbnHmlhpLrRjYe07zW0RrjNmM1XVsTXZtUnmPkF9k9U1sOuX+QS++lnutFgU81yiFbzu8zUdf/SD9xj2FfH+wP27yjiscyHMYxaAfOV3ztyZNBTL2C0i+c/h7YaxhslZLMQJBAOfCS2DU9PLIPvNrrjkvtUSUJqEwElr4bAp9R9AvwoAx1qaUhU71WzUYr6wyR+T1CuUxj0/pmiRB2F6oqyrFK+0CQQCtgbZ8dYDAlmyyQ64ZbQnA+dwNU39uyNtzbDweqK+y50UFcKpnikWx00b6L58mLrw0IKB/8S7x0amdZlYZMRsnAkEA4VZHhiHo/Dn5AyLaph2d6M0HdkfQQQUzv0sqTOBzA8Pxicv0hd4HzWtwO0Q0JQigjFIQnslqJwCiiP8EVjSZzQJBAIqNYJo2guBHvvkDjs2DAxz06cJCgSqIfqXHMqMQ9W0ZvUZA1/LiuhDstGspCB/HhkbiHwjMIj68vIOSqwJm8lUCQC7ItHFWvMquS16hvs7tSYrZnoYHLrpKjNA1RdjZ1GTnI5lP3myJsOXEv/zZ4rBrUTwwTgjVw18nqSgXC7W+X1k=

# token配置信息
Token:
  Signature: FSFDGVB468vfdxVC1XDc1D6FV816F8V5fcg65B1VGCb6c86bVC65G
  # minutes
  ExpiredTime:
    # 2h
    Common: 120
    # 1d
    Refresh: 1440

# 外部系统信息
QH:
  PublicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCIzao+1iWqAmoZ7SQoM3tZBY5CElYfGvz+55PqoV3hDjdJjizNlz7dtfNtV7Q1PBBKyEwzQggY4pHAo8NSTtWf58gToqP/wbkEu+MGZWDp6UyzyaoJq4bm4qbF5YJ2/HEPBlxitmopvt69xkIyCnwBGZ7Y6bGjUO5emYm1oHL7DwIDAQAB

